project_id = "tahfemcxtbbixsvsurfq"

[functions.generate-notes]
verify_jwt = false

[functions.find-video]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.adaptive-question]
verify_jwt = false

[functions.analyze-weakness]
verify_jwt = false

[functions.fix-weak-areas-quiz]
verify_jwt = false
